server:
  port: 8082
spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/${MONGO_DB:catalogdb}
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health,info
